### ISSUE TITLE
jenny seems to have leaky state

### ISSUE THREAD

**Issue by mpictor** [bmustiata/jenny#26] opened 2018-08-15 19:58 UTC
Besides #25, another problem I noticed was that, after running jenny in one dir and then another, the output from the *second* run referenced dirs from the *first* run. This is definitely not a case of concatenated logs - I made certain to start fresh.

Even removing **all** docker containers and images and deleting `/tmp/jenny` did **not** cause this to stop. I do not know where else jenny could be storing state, but this behavior is concerning for a few different reasons.
* Running in one dir shouldn't have any impact on future runs in any other dir
* State shouldn't be stored except in obvious or documented locations, so that it can cleaned up if it gets corrupted or grows too large.
* Hidden persistent state could be a security hazard _if_ it contained credentials or other sensitive information.

Evidence of this can be seen in the file attached to #25, [jenny-out.txt](https://github.com/bmustiata/jenny/files/2291458/jenny-out.txt): search for `buildfarm`.

**Comment by bmustiata** [comment] 2018-08-15 22:14
I can't mentally see your Jenkinsfile, but maybe the workspace is not being clean up? You should always do that in your node:

```groovy
node {
    deleteDir()
    checkout scm
    // actual build steps
}
```

Surprisingly enough, this is the behavior of Jenkins that it's being emulated, and is intentional. Nodes are not being automatically cleaned up, and they are being recycled. There will be junk on the Jenkins nodes.

**Comment by bmustiata** [comment] 2018-08-15 22:26
The data is not stored in `jenny`, but when you do `checkout scm` this will actually just do a copy of the project into the `/tmp/jenny/workspace/PROJECT_NAME/workspace`. The `Jenkinsfile` it's still being evaluated from the original project folder, since we're already evaluating it at this stage, when we reach `checkout scm`.

If the error still happens, it's probably still an error in the project's Jenkinsfile. From what I can see in the exception it seems that the list of parameters is not correctly closed, or created (missing comma between parameters?).

**Comment by mpictor** [comment] 2018-08-16 16:07
There was a mistake in its Jenkinsfile. What I don't understand is why that Jenkinsfile was being used in what ought to be an unrelated run of jenny.

**Comment by bmustiata** [comment] 2018-08-16 17:06
I don't know without seeing the Jenkinsfiles. Maybe the same project name is being used multiple times? I'm going to wait a few days, and if you can't reproduce it I'll close the issue.

**Comment by mpictor** [comment] 2018-08-16 18:39
Ok.

So far, I only see it when running `./jenny` in the jenny repo. As you've noted, that is probably trying to do weird things such as run docker inside docker :)

**Closed** 2018-08-20 20:31 UTC
